#!/usr/bin/env bash
# install and configure nginx web server

sudo apt-get -y update
sudo apt-get -y install  nginx
file=/usr/share/nginx/html/index.html
sudo bash -c "echo Hello World! > $file"
sudo sed -i 's/listen 80 default_server;/listen 80;/g' \
	/etc/nginx/sites-available/default
sudo sed -i 's@/var/www/html;@/usr/share/nginx/html;@' \
	/etc/nginx/sites-available/default
service nginx start
service nginx restart
