#!/usr/bin/env bash
# redirect a page pamanetly

sudo apt-get -y update
sudo apt-get -y install  nginx
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a \
\
    location \/redirect_me \{ \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    \}' /etc/nginx/sites-available/default
service nginx restart
