#!/usr/bin/env bash
# configures nginx to return a custom header

sudo apt-get -y update
sudo apt-get -y install  nginx
hostname="add_header X-Served-By $(hostname)"
sudo sed -i "21i $hostname;" /etc/nginx/sites-available/default
sudo service nginx restart
