#!/usr/bin/env bash
# install and configure HAproxy load balancer

sudo apt update
sudo apt -y install haproxy
config="
frontend myfrontend
	bind *:80
	mode http
	default_backend mybackend
backend mybackend
	sever 482147-web-01 18.207.139.215:80 check
	sever 482147-web-02 18.204.3.2:80 check"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
