#!/usr/bin/env bash
#if statement implementation

count=0
while [ $count -lt 12 ]
do
	echo "Hour: $count"
	min_cnt=1
	while [ $min_cnt -le 59 ]
	do
		echo "$min_cnt"
		((min_cnt++))
	done
	
	((count++))
done
